### PR TITLE
resolve #24 add implicit flush for $timeout and $httpBackend

### LINKED ISSUE #24: Add support for $httpBackend promises
When using this with the httpBackend mock I have to call $httpBackend.flush() before I can expect the promise to be resolved. It would be nice if the backend was flushed by this framework. I know that this is tricky because the flush method throws an exception if there are no pending requests.

### PR DESCRIPTION
**Pull request by casmith**
This adds an implicit .flush() call for $httpBackend and $timeout after triggering the digest cycle. If the .flush() is not needed, the error that is thrown as a result is suppressed. Any other errors generated by triggering the .flush() are rethrown.

### CODE REVIEW

File: source/source.js [hunk 1]
```diff
@@ -42,6 +46,24 @@ var installPromiseMatchers;
 
     $scope.$apply(); // Trigger Promise resolution
 
+    // Trigger $httpBackend flush if any requests are pending
+    try {
+      $httpBackend.flush();
+    } catch (err) {
+      if (err.message !== 'No pending request to flush !') {
```
Comment (bvaughn) [inline source/source.js]: String-matching on an error message seems very questionable. (It would be different to match an error code, since those are implied to be relatively stable, but this... I feel uneasy about.)

Granted neither of these strings have changed since _Oct 22, 2013_ so maybe this is just me being overly cautious...

I don't use this library anymore since I haven't worked with Angular 1.x for over a year now. So I guess I'll defer to your judgement in terms of the convenience trade-off here vs the "risk" of the inline string. If any unexpected problems are reported against this behavior though, I'll have to remove it. Seem reasonable?

Comment (casmith) [inline source/source.js]: I agree that string matching is not the best approach, but there is no error code on the Error object, and there's no way with $httpBackend or $timeout to find out of there is something to flush without flushing. The good news is, the unit tests do break if the error messages changes. 

Yes, your terms are very reasonable! Thanks for reviewing so quickly.

**Comment by bvaughn** [comment]
2.1.0 has just been released with this change merged in. Thank you for your contribution. :)
